// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "doc",
      label: "1. Plan de cours",
      id: "cours/plan-cours",
    },
    {
      type: "doc",
      label: "2. Présentation TP1",
      id: "cours/plan-cours",
    },
    {
      type: "doc",
      label: "3. Impératif",
      id: "cours/imperatif",
    },
    {
      type: "doc",
      label: "4. Impératif",
      id: "cours/imperatif",
    },
    {
      type: "doc",
      label: "5. Librairies",
      id: "cours/librairies",
    },
    {
      type: "doc",
      label: "6. Intro aux tests",
      id: "cours/intro-tests",
    },
    {
      type: "doc",
      label: "7. Structurer son code",
      id: "cours/structurer-code",
    },
    {
      type: "doc",
      label: "8. Intégration",
      id: "cours/integration1",
    },
    {
      type: "doc",
      label: "9. Formatif pratique",
      id: "cours/formatif-pratique",
    },
    {
      type: "doc",
      label: "10. Examen Intra",
      id: "cours/examen-intra",
    },
    {
      type: "doc",
      label: "11. Intro Android",
      id: "cours/intro-android",
    },
    {
      type: "doc",
      label: "12. Activités et navigation",
      id: "cours/activites-navigation",
    },
    {
      type: "doc",
      label: "13. Tiroir de navigation",
      id: "cours/tiroir-navigation",
    },
    {
      type: "doc",
      label: "14. Tiroir de navigation",
      id: "cours/tiroir-navigation",
    },
    {
      type: "doc",
      label: "15. Listes i18n",
      id: "cours/listes-i18n",
    },
    {
      type: "doc",
      label: "16. Graphique",
      id: "cours/graphique",
    },
    {
      type: "doc",
      label: "17. Intégration",
      id: "cours/integration2",
    },
    {
      type: "doc",
      label: "18. Pile d'appels et exceptions",
      id: "cours/exceptions",
    },
    {
      type: "doc",
      label: "19. Composable et syntaxe",
      id: "cours/composable-syntaxe",
    },
    {
      type: "doc",
      label: "20. Structurer son code",
      id: "cours/structurer-code-service",
    },
    {
      type: "doc",
      label: "21. Etat",
      id: "cours/etat",
    },
    {
      type: "doc",
      label: "22. Etat",
      id: "cours/etat",
    },
    {
      type: "doc",
      label: "23. Listes (état)",
      id: "cours/listes-etat",
    },
    {
      type: "doc",
      label: "24. Tests",
      id: "cours/tests",
    },
    {
      type: "doc",
      label: "25. Tests",
      id: "cours/tests",
    },
    {
      type: "doc",
      label: "26. Copilot et moi",
      id: "cours/copilot-et-moi",
    },
    {
      type: "doc",
      label: "27. Intégration",
      id: "cours/integration3",
    },
    {
      type: "doc",
      label: "28. Intégration",
      id: "cours/integration-suite",
    },
    {
      type: "doc",
      label: "29. Formatif final",
      id: "cours/formatif-final",
    },
    {
      type: "doc",
      label: "30. Examen final",
      id: "cours/examen-final",
    },
  ],
  recettes: [
    {
      type: "autogenerated",
      dirName: "02-recettes",
    },
  ],
  tp: [
    {
      type: "autogenerated",
      dirName: "03-tp",
    },
  ],
};

module.exports = sidebars;
